server:
  port: 9090
spring:
  datasource:
    password: Zhuchb@0509
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/java_scaffold?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      stat-view-servlet:
        login-password: 123456
        login-username: admin
        url-pattern: /druid/*
        enabled: true
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 500
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: redistest
      database: 0
      lettuce:
        pool:
          enabled: true  # 启用连接池
          max-active: 8  # 最大活跃连接数
          max-idle: 4    # 最大空闲连接数
          min-idle: 1    # 最小空闲连接数
  cache:
    type: redis
    redis:
      time-to-live: 600000
user:
  service:
    lock: true